### PR TITLE
Issue 267 paragraph update output messages with no data

### LINKED ISSUE #267: Server sends empty PARAGRAPH_UPDATE_OUTPUT messages
**Describe the bug**
Some PARAGRAPH_UPDATE_OUTPUT messages contain no data when running a paragraph.

**Expected behavior**
All PARAGRAPH_UPDATE_OUTPUT messages should contain some data.

**How to reproduce**
Run a paragraph with large results, observer the rececived messages
**Software version**
3.2.0

### PR DESCRIPTION
**Pull request by Laukkala**
## Description
fixes #267

Default invocation of InterpreterOutput.clear() sends a message with empty data to frontend, which is causing problems with UI. This PR changes that behaviour by simply supplying a 'false' boolean to the method.

#### General

- [x] I have checked that my test files and functions have meaningful names.
- [x] I have checked that each test tests only a single behavior.
- [x] I have done happy tests.
- [x] I have tested only my own code.
- [x] I have tested at least all public methods.

#### Assertions

- [x] I have checked that my tests use assertions and not runtime overhead.
- [x] I have checked that my tests end in assertions.
- [x] I have checked that there is no comparison statements in assertions.
- [x] I have checked that assertions are in tests and not in helper functions.
- [x] I have checked that assertions for iterables are outside of for loops and both sides of the iteration blocks.
- [x] I have checked that assertions are not tested inside consumers.

#### Testing Data

- [x] I have tested algorithms and anything else with the possibility of unbound growth.
- [x] I have checked that all testing data is local and fully replaceable or reproducible or both.
- [x] I have checked that all test files are standalone.
- [x] I have checked that all test-specific fake objects and classes are in the test directory.
- [x] I have checked that my tests do not contain anything related to customers, infrastructure or users.
- [x] I have checked that my tests do not contain non-generic information.
- [x] I have checked that my tests do not do external requests and are not privately or publicly routable.

#### Statements

- [x] I have checked that my tests do not use throws for exceptions.
- [x] I have checked that my tests do not use try-catch statements.
- [x] I have checked that my tests do not use if-else statements.

#### Java

- [x] I have checked that my tests for Java uses JUnit library.
- [x] I have checked that my tests for Java uses JUnit utilities for parameters.

#### Other

- [x] I have only tested public behavior and not private implementation details.
- [x] I have checked that my tests are not (partially) commented out.
- [x] I have checked that hand-crafted variables in assertions are used accordingly.
- [x] I have tested [Object Equality](https://docs.oracle.com/javase/6/docs/api/java/lang/Object.html#equals%28java.lang.Object%29).
- [x] I have checked that I do not have any manual tests or I have a valid reason for them and I have explained it in the PR description.

### Code Quality

- [x] I have checked that my code follows metrics set in Procedure: Class Metrics.
- [x] I have checked that my code follows metrics set in Procedure: Method Metrics.
- [x] I have checked that my code follows metrics set in Procedure: Object Quality.
- [x] I have checked that my code does not have any NULL values.
- [x] I have checked my code does not contain FIXME or TODO comments.

### CODE REVIEW

**Comment by Laukkala** [comment]
Comment on removed test:
Removed test was added to validate the behaviour of a bugfix to an issue where making a pagination request cleared the output of the Notebook after a page reload. Changes made since then have made this test redundant, as pagination requests no longer requires clearing InterpreterOutput, but the test itself was never removed.

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java [hunk 1]
```diff
@@ -228,7 +228,15 @@ public void testClearParagraphResultsOnNewDataset(){
...
+        Assertions.assertEquals(0,listener.numberOfResetCalls());
+
+        // Simulate DPL receiving another batch of data.
+        Assertions.assertDoesNotThrow(()->{
+            dtTableDatasetNg.setParagraphDataset(testDs);
+        });
+        Assertions.assertEquals(2,listener.numberOfUpdateCalls());
+        Assertions.assertEquals(0,listener.numberOfResetCalls());
+
     }
```
Comment (MoonBow-1) [inline spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java:240]: Slight suggestion for formatting

```suggestion
        // Simulate DPL receiving another batch of data.
        Assertions.assertDoesNotThrow(()->{
            dtTableDatasetNg.setParagraphDataset(testDs);
        });
        
        Assertions.assertEquals(2,listener.numberOfUpdateCalls());
        Assertions.assertEquals(0,listener.numberOfResetCalls());
}
```

**Review by MoonBow-1 — APPROVED** [review]
Aside from the slight formatting, LGTM

**Review by MoonBow-1 — APPROVED** [review]
LGTM now that there is a test for the changed behavior

**Review by kortemik — APPROVED** [review]
