### PR TITLE
Issue 268 draw not being incremented

### LINKED ISSUE #268: Draw in PARAGRAPH_UPDATE_OUTPUT is not incremented when a new batch is received from interpreter
**Describe the bug**
Currently draw is not being incremented when a new batch is received from interpreter, instead being incremented on a pagination request. Each batch received resets draw back to 1.

**Expected behavior**
Draw should be incremented when a new batch is received from interpreter.
If the schema of the data changes, draw should be reset back to 1.

**How to reproduce**
Run paragraph that returns multiple batches worth of data, observe PARAGRAPH_UPDATE_OUTPUT messages received.

**Screenshots**

**Software version**
3.3.0

### PR DESCRIPTION
**Pull request by Laukkala**
## Description
fixes #268 

DTTableDatasetNg now keeps track of changes in data Schema when receiving new batches of data from DPL.
Whenever a new batch is received, the draw value is incremented by 1. When a change in Schema is detected, the draw value is reset to 1.

This behaviour is expected by DataTables on the UI.
Implementation contains nulls as removing them would require large refactoring

#### General

- [x] I have checked that my test files and functions have meaningful names.
- [x] I have checked that each test tests only a single behavior.
- [x] I have done happy tests.
- [x] I have tested only my own code.
- [x] I have tested at least all public methods.

#### Assertions

- [x] I have checked that my tests use assertions and not runtime overhead.
- [x] I have checked that my tests end in assertions.
- [x] I have checked that there is no comparison statements in assertions.
- [x] I have checked that assertions are in tests and not in helper functions.
- [x] I have checked that assertions for iterables are outside of for loops and both sides of the iteration blocks.
- [x] I have checked that assertions are not tested inside consumers.

#### Testing Data

- [x] I have tested algorithms and anything else with the possibility of unbound growth.
- [x] I have checked that all testing data is local and fully replaceable or reproducible or both.
- [x] I have checked that all test files are standalone.
- [x] I have checked that all test-specific fake objects and classes are in the test directory.
- [x] I have checked that my tests do not contain anything related to customers, infrastructure or users.
- [x] I have checked that my tests do not contain non-generic information.
- [x] I have checked that my tests do not do external requests and are not privately or publicly routable.

#### Statements

- [x] I have checked that my tests do not use throws for exceptions.
- [x] I have checked that my tests do not use try-catch statements.
- [x] I have checked that my tests do not use if-else statements.

#### Java

- [x] I have checked that my tests for Java uses JUnit library.
- [x] I have checked that my tests for Java uses JUnit utilities for parameters.

#### Other

- [x] I have only tested public behavior and not private implementation details.
- [x] I have checked that my tests are not (partially) commented out.
- [x] I have checked that hand-crafted variables in assertions are used accordingly.
- [ ] I have tested [Object Equality](https://docs.oracle.com/javase/6/docs/api/java/lang/Object.html#equals%28java.lang.Object%29).
- [x] I have checked that I do not have any manual tests or I have a valid reason for them and I have explained it in the PR description.

### Code Quality

- [x] I have checked that my code follows metrics set in Procedure: Class Metrics.
- [x] I have checked that my code follows metrics set in Procedure: Method Metrics.
- [x] I have checked that my code follows metrics set in Procedure: Object Quality.
- [ ] I have checked that my code does not have any NULL values.
- [x] I have checked my code does not contain FIXME or TODO comments.

### CODE REVIEW

File: spark/dpl-interpreter/src/main/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNg.java [hunk 1]
```diff
@@ -62,14 +62,16 @@
...
 
 public final class DTTableDatasetNg extends AbstractUserInterfaceElement {
     // FIXME Exceptions should cause interpreter to stop
 
     private final Lock lock = new ReentrantLock();
 
     private List<String> datasetAsJSON = null;
-    private JsonArray schemaHeadersJson;
+    private DTHeader schemaHeaders;
+    private int draw;
```
Comment (MoonBow-1) [inline spark/dpl-interpreter/src/main/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNg.java]: I would suggest renaming this to `drawCount` for better clarity

File: spark/dpl-interpreter/src/main/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNg.java [hunk 2]
```diff
@@ -81,7 +83,8 @@ public final class DTTableDatasetNg extends AbstractUserInterfaceElement {
 
     public DTTableDatasetNg(InterpreterContext interpreterContext) {
         super(interpreterContext);
-        schemaHeadersJson = Json.createArrayBuilder().build();
+        schemaHeaders = new DTHeader();
+        draw = 1;
     }
```
Comment (MoonBow-1) [inline spark/dpl-interpreter/src/main/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNg.java]: I would create a new ctor for the three values, and then reference the "primary" ctor from this

Comment (MoonBow-1) [reply spark/dpl-interpreter/src/main/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNg.java]: Also the argument can be made `final`

File: spark/dpl-interpreter/src/main/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNg.java [hunk 3]
```diff
@@ -152,11 +162,11 @@ public JsonObject SearchAndPaginate(int draw, int start, int length, String sear
 
         // ui formatting
         JsonArray formated = dataStreamParser(paginatedList);
-
+        JsonArray schemaHeadersAsJSON = schemaHeaders.json();
```
Comment (MoonBow-1) [inline spark/dpl-interpreter/src/main/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNg.java]: `schemaHeadersAsJSON` can be made final

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTHeaderTest.java [hunk 4]
```diff
@@ -91,6 +91,15 @@ public void testJSONDTHeader() throws ParserConfigurationException, TransformerE
...
     }
 
+    @Test
+    public void testEmptyDTHeader() {
+        JsonArray json = Json.createArrayBuilder()
+                .build();
+        String e = json.toString();
+        DTHeader dtHeader = new DTHeader();
+        assertEquals(e, dtHeader.json().toString());
+    }
```
Comment (MoonBow-1) [inline spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTHeaderTest.java:101]: Variables can be made final, and more clarity to variable names would be appreciated

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java [hunk 5]
```diff
@@ -182,6 +208,21 @@ private List<Row> makeRowsList(long _time, Long id, String _raw, String index, S
...
+            // creates rows in inverse order
+            Timestamp timestamp = Timestamp.from(Instant.ofEpochSecond(_time+amount));
+            Row row = RowFactory.create(timestamp, id, _raw, index, sourcetype, host, source, partition, offset, origin, extraField);
+            rowArrayList.add(row);
+            amount--;
+        }
+
+
+        return rowArrayList;
+    }
```
Comment (MoonBow-1) [inline spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java]: Variables can be made final

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java [hunk 6]
```diff
@@ -113,6 +107,38 @@ public class DTTableDatasetNgTest {
...
+                    new StructField("host", DataTypes.StringType, false, new MetadataBuilder().build()),
+                    new StructField("source", DataTypes.StringType, false, new MetadataBuilder().build()),
+                    new StructField("partition", DataTypes.StringType, false, new MetadataBuilder().build()),
+                    new StructField("offset", DataTypes.LongType, false, new MetadataBuilder().build()),
+                    new StructField("origin", DataTypes.StringType, false, new MetadataBuilder().build()),
+                    new StructField("extraData",DataTypes.StringType, false, new MetadataBuilder().build())
+            }
+    );
+
+    Dataset<Row> testDs2 = sparkSession.createDataFrame(rows2, testSchema2);
```
Comment (MoonBow-1) [inline spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java]: Can be made `private final`

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java [hunk 7]
```diff
@@ -113,6 +107,38 @@ public class DTTableDatasetNgTest {
...
+
```
Comment (MoonBow-1) [inline spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java]: These variables are becoming quite long, can Fake objects be considered, or moving these variables to the test methods that use them?

`rows2`, `testSchema2` and `testDs2` are only used in the `testIncrementDraw()` test

**Review by MoonBow-1 — CHANGES_REQUESTED** [review]

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java (hunk 7 above)
Comment (Laukkala) [reply spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java]: Simplified creation of test Datasets into one DPLTestData class within the test in commit https://github.com/teragrep/zep_01/pull/269/commits/fa6ab1e0c0530d5e797490f42d9c3d290cb76ed7

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java (hunk 6 above)
Comment (Laukkala) [reply spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java]: Changed in commit https://github.com/teragrep/zep_01/commit/fa6ab1e0c0530d5e797490f42d9c3d290cb76ed7

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java (hunk 5 above)
Comment (Laukkala) [reply spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java]: Added in commit [2568e4b](https://github.com/teragrep/zep_01/pull/269/commits/2568e4bb1c94fc48a9f04a07c4e47c6e713df0f3)

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTHeaderTest.java (hunk 4 above)
Comment (Laukkala) [reply spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTHeaderTest.java:101]: Made these final, added some comments and renamed variables in commit [c796d2b](https://github.com/teragrep/zep_01/pull/269/commits/c796d2bbe2aa498a6686dc36fd1c02b314e61f57)

File: spark/dpl-interpreter/src/main/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNg.java (hunk 2 above)
Comment (Laukkala) [reply spark/dpl-interpreter/src/main/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNg.java]: Fixed in commit [ae6e90c](https://github.com/teragrep/zep_01/pull/269/commits/ae6e90c7de4af88ab0547b8e1ef6c4623013fdcf)

File: spark/dpl-interpreter/src/main/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNg.java (hunk 1 above)
Comment (Laukkala) [reply spark/dpl-interpreter/src/main/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNg.java]: Fixed in commit [ae6e90c](https://github.com/teragrep/zep_01/pull/269/commits/ae6e90c7de4af88ab0547b8e1ef6c4623013fdcf)

File: spark/dpl-interpreter/src/main/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNg.java (hunk 3 above)
Comment (Laukkala) [reply spark/dpl-interpreter/src/main/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNg.java]: Fixed in commit [ae6e90c](https://github.com/teragrep/zep_01/pull/269/commits/ae6e90c7de4af88ab0547b8e1ef6c4623013fdcf)

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java (hunk 7 above)
Comment (MoonBow-1) [reply spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java]: The new `DPLTestData` class is better, but I'm not sure if it should be an inner class of `DTTableDatasetNgTest`, maybe @eemhu would know the correct place for this in the `test` directory?

Comment (Laukkala) [reply spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNgTest.java]: It's probably clearer to have this as a separate file instead of hiding the data generation in a helper class. Moved this into a separate file in commit [c7fe60d](https://github.com/teragrep/zep_01/pull/269/commits/c7fe60def2ecd80c33752789b085b11ba9555979)

File: spark/dpl-interpreter/src/main/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNg.java [hunk 8]
```diff
@@ -99,12 +101,19 @@ public void setParagraphDataset(Dataset<Row> rowDataset) {
 
         try {
             lock.lock();
+            // Reset draw when schema changes
+            if(!schemaHeaders.schema().equals(rowDataset.schema())){
```
Comment (kortemik) [inline spark/dpl-interpreter/src/main/java/com/teragrep/pth_07/ui/elements/table_dynamic/DTTableDatasetNg.java:105]: can schema change between runs as internalInterpret is rerun foreach of the interpretations and schema can not change once spark has determined it

**Review by kortemik — DISMISSED** [review]

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java [hunk 9]
```diff
@@ -0,0 +1,100 @@
...
+import org.apache.spark.sql.SparkSession;
+import org.apache.spark.sql.types.StructType;
+
+import java.sql.Timestamp;
+import java.time.Instant;
+import java.util.ArrayList;
+import java.util.Arrays;
+import java.util.List;
+
+public class TestDPLData {
```
Comment (MoonBow-1) [inline spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java]: Class can be final

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java [hunk 10]
```diff
@@ -0,0 +1,100 @@
...
+        private final SparkSession sparkSession;
+        private final StructType schema;
+
+        public TestDPLData(SparkSession sparkSession, StructType schema){
```
Comment (MoonBow-1) [inline spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java]: Arguments can be made final

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java [hunk 11]
```diff
@@ -0,0 +1,100 @@
...
+        }
+
+        /**
+         * Tries to generate a dataset of size 'amount' with default values corresponding to varargs 'values'
+         * @param amount - desired number of rows in the dataset
+         * @param values - varargs specifying the default values to fill into the dataset.
+         * @return
+         */
+
+        public Dataset<Row> createDataset(int amount, Object ... values){
```
Comment (MoonBow-1) [inline spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java]: Arguments can be made final

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java [hunk 12]
```diff
@@ -0,0 +1,100 @@
...
+            return sparkSession.createDataFrame(rows, schema);
+        }
+
+        /**
+         * Generates a List of Rows based on given values.
+         * @param amount - Number of rows to generate
+         * @param values - Default values to add for each Row. If first value given is a Timestamp, it will be incremented by one for each Row.
+         * @return
+         */
+        private List<Row> rowList(int amount, Object ... values){
```
Comment (MoonBow-1) [inline spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java]: `values` can be made final

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java [hunk 13]
```diff
@@ -0,0 +1,100 @@
...
+        public TestDPLData(SparkSession sparkSession, StructType schema){
+            this.sparkSession = sparkSession;
+            this.schema = schema;
+        }
+
+        /**
+         * Tries to generate a dataset of size 'amount' with default values corresponding to varargs 'values'
+         * @param amount - desired number of rows in the dataset
+         * @param values - varargs specifying the default values to fill into the dataset.
+         * @return
```
Comment (MoonBow-1) [inline spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java]: Return description is missing

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java [hunk 14]
```diff
@@ -0,0 +1,100 @@
...
+        public Dataset<Row> createDataset(int amount, Object ... values){
+            final List<Row> rows = rowList(amount,values);
+            return sparkSession.createDataFrame(rows, schema);
+        }
+
+        /**
+         * Generates a List of Rows based on given values.
+         * @param amount - Number of rows to generate
+         * @param values - Default values to add for each Row. If first value given is a Timestamp, it will be incremented by one for each Row.
+         * @return
```
Comment (MoonBow-1) [inline spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java]: Return description is missing

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java [hunk 15]
```diff
@@ -0,0 +1,100 @@
...
+            final List<Object> valueList = Arrays.asList(values);
+            final ArrayList<Row> rowArrayList = new ArrayList<>();
+            while (amount > 0) {
+                if(valueList.get(0) instanceof Timestamp){
+                    valueList.set(0, Timestamp.from(Instant.ofEpochSecond(amount)));
+                }
+                final Row row = RowFactory.create(valueList.toArray());
+                rowArrayList.add(row);
+                amount--;
+            }
```
Comment (MoonBow-1) [inline spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java]: This loop modifies the `amount` argument, so I'm not sure if this is the correct way to loop, since it can be done with, which would allow both the arguments to be immutable:

```java
private List<Row> rowList(final int amount, final Object ... values){
    final List<Object> valueList = Arrays.asList(values);
    final ArrayList<Row> rowArrayList = new ArrayList<>();
    for (int i = amount; i > 0; i--) {
        if(valueList.get(0) instanceof Timestamp){
            valueList.set(0, Timestamp.from(Instant.ofEpochSecond(i)));
        }
        final Row row = RowFactory.create(valueList.toArray());
        rowArrayList.add(row);
    }
    return rowArrayList;
}
```

**Review by MoonBow-1 — CHANGES_REQUESTED** [review]

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java (hunk 9 above)
Comment (Laukkala) [reply spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java]: Fixed in commit [32345ab](https://github.com/teragrep/zep_01/pull/269/commits/32345ab732383fbf2831cb409a751e5644155fe6)

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java (hunk 10 above)
Comment (Laukkala) [reply spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java]: Fixed in commit [32345ab](https://github.com/teragrep/zep_01/pull/269/commits/32345ab732383fbf2831cb409a751e5644155fe6)

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java (hunk 11 above)
Comment (Laukkala) [reply spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java]: Fixed in commit [32345ab](https://github.com/teragrep/zep_01/pull/269/commits/32345ab732383fbf2831cb409a751e5644155fe6)

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java (hunk 12 above)
Comment (Laukkala) [reply spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java]: Fixed in commit [32345ab](https://github.com/teragrep/zep_01/pull/269/commits/32345ab732383fbf2831cb409a751e5644155fe6)

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java (hunk 13 above)
Comment (Laukkala) [reply spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java]: Fixed in commit [32345ab](https://github.com/teragrep/zep_01/pull/269/commits/32345ab732383fbf2831cb409a751e5644155fe6)

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java (hunk 14 above)
Comment (Laukkala) [reply spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java]: Fixed in commit [32345ab](https://github.com/teragrep/zep_01/pull/269/commits/32345ab732383fbf2831cb409a751e5644155fe6)

File: spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java (hunk 15 above)
Comment (Laukkala) [reply spark/dpl-interpreter/src/test/java/com/teragrep/pth_07/ui/elements/table_dynamic/testdata/TestDPLData.java]: Fixed in commit [32345ab](https://github.com/teragrep/zep_01/pull/269/commits/32345ab732383fbf2831cb409a751e5644155fe6)

**Review by MoonBow-1 — APPROVED** [review]

**Review by kortemik — APPROVED** [review]
